### PR TITLE
add batman ecl/tr, constant ramp, python versions of nnint and bilinint

### PR DESCRIPTION
**Pull request by lkreidberg**
HI Kevin! I added several models:

- pnnint and pbilinint: python versions of nnint and bilintint
- constant: a constant ramp model (needed since batman models are normalized to unity)
- batman_trquad: batman transit model with quadratic limb darkening
- batman_ecl: batman eclipse model

Two comments: I had to give the batman_ecl model a 'sinusoidal' type to get the plots to display correctly. (I think this is because batman eclipses have the in-eclipse flux normalized to 1, and the out-of-eclipse flux is 1 + fpfs).

I also found that I have to put the list batman_trquad *before* batman_ecl in my _params.py file. Otherwise only the eclipse model is calculated, not sure why.

Spiderman models coming soon!

### CODE REVIEW

**Comment by lkreidberg** [comment]
I added several spiderman models too:

spiderman_zhang: models phase curves with the Zhang & Showman 2017 analytic model
spiderman_spot: planet has a hot spot with variable size, location, and temperature
spiderman_rock: the simple rock analytic model from Kreidberg & Loeb 2016
spiderman_sph: spherical harmonics

For the spiderman models, it would be nice to pass in a few parameters through the etc list (e.g., the path to the Spitzer filter response function). I didn't see an easy way to do this right off the bat, though, so this is on the TODO list.

**Review by kevin218 — CHANGES_REQUESTED** [review]
Lines 1431 and 1441 of python_models.py were modified to `elif model[i] == 'pnnint'` and `elif model[i] == 'pbilinint':` instead of adding new `elif` functions for `pnnint` and `pbilint`.  In the current implementation, `nnint` and `bilinint` cannot be called.  Please add `elif` statements for these two functions.

**Comment by kevin218** [comment]
> For the spiderman models, it would be nice to pass in a few parameters through the etc list (e.g., the path to the Spitzer filter response function). I didn't see an easy way to do this right off the bat, though, so this is on the TODO list.

I agree that it isn't obvious how to do this, but it should be feasible.  Please create a GitHub issue with sufficient detail for me to understand your needs and I will look into adding this functionality through p6model.py.

**Comment by lkreidberg** [comment]
Got it - I changed this back. Thanks!

**Review by kevin218 — CHANGES_REQUESTED** [review]
Line 1438 should read `myfuncs.append(mc.nnint)`.
Line 1448 should read `myfuncs.append(mc.bilinint)`.

**Comment by lkreidberg** [comment]
Fixed it!

**Review by kevin218 — APPROVED** [review]

**Pull request merged**
